### ISSUE TITLE
道の自動生成について

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#1]
ステージを変える前は上手く生成できたのですが、ステージを変えたあと、それに合わせてスクリプトの数値を変えたつもりなのですが上手く生成されません。どうしてでしょうか。最初のターンだけ上手くいきません。

スクリプトはCreateScriptをメインカメラにつけています。

解決方法を教えてください。

**Comment by Ayarin226** [comment]
ステージをどう変えたら動かなくなったのか教えてくださいー！
数値がうまく設定にあってないんじゃないかな？
Player？の座標と見比べながら試して見てください……！

**Comment by moooe** [comment]
キューブから、街のアセットに変えました！
街ごと生成するようにしたいです。

**Comment by Ayarin226** [comment]
なるほど！ちょっと見てみるね
生成っていうより移動であってる？

**Comment by moooe** [comment]
あ！確かに！移動ですね！
２つの道路を交互に出現させるって感じです！

**Comment by Ayarin226** [comment]
考え方として、
Street1の半分くらいまでキャラが来たらStreet2をStreet1の端に移動
Street2の半分くらいまでキャラが来たらStreet1をStreet2の端に移動
ってやっているのは良いと思う！

順番としては
```
もし、キャラがStreet1の半分まで来ていたら
1. Street2のz座標をStreet 2個分ずらす
2. ボーダーラインをStreet 1個分ずらす
```
が良いかなって思います。

問題は、if文で道の座標を使って判断しているところかな？
キューブからアセットに変更したから、if文で使っている座標が自分の認識している座標とずれていそう

**Comment by Ayarin226** [comment]
こんな感じでうまくいったよー！

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CreateScript : MonoBehaviour
{

    public GameObject Street1;
    public GameObject Street2;

    float border = -62.5f;

    void Update()
    {
        if (transform.position.z > border)
        {
            MoveStreet();
        }
    }

    void MoveStreet()
    {
        if (Street1.transform.position.z < Street2.transform.position.z)
        {
            Street1.transform.position += new Vector3(0, 0, 190);
            border += 95;
        }
        else
        {
            Street2.transform.position += new Vector3(0, 0, 190);
            border += 95;
        }
    }
}
```

道の座標とborderラインを比べるんじゃなくて、
道2つを比べて後ろの方にある道を移動させるようにしました！

**Comment by moooe** [comment]
丁寧にありがとうございます！！
すぐには理解できないけどスクリプトとにらめっこして頑張って理解します！笑

**Comment by Ayarin226** [comment]
そんなに難しいことしているわけではないので今までのコードがかけていたなら理解できると思う！
理解できなかったりまたわからないことがあったら気軽に言って〜！

**Comment by moooe** [comment]
わかりました！ありがとございます！

それとGitHubについてなのですが、issueの返信が来た時に通知を受け取るようにすることって出来ますか？

**Comment by Ayarin226** [comment]
リポジトリをウォッチしていたらメールがくると思う……！

**Comment by moooe** [comment]
今見たら来ていました！ありがとうございます！

**Comment by moooe** [comment]
190ってStreetの一つの長さですか？

**Comment by Ayarin226** [comment]
`
Street2のz座標をStreet 2個分ずらす
`
なので2つの長さですね

**Comment by moooe** [comment]
すみません。。
なんで２つ分ずらすのかわかりません

**Comment by Ayarin226** [comment]
1つ分しかずらさないと、隣（前）にある道に重なっちゃうよね？
<img width="530" alt="2018-05-06 15 33 33" src="https://user-images.githubusercontent.com/38731389/39670577-e13e4932-5142-11e8-996f-8ba5ff6d312f.png">

**Comment by moooe** [comment]
あああ！！理解できました！！ありがとうございます！
