### ISSUE TITLE
キャラクターのジャンプの高さについて

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#2]
今アセットストアからインポートしたキャラクターを使っているのですが、ジャンプ力がなさ過ぎて何も飛び越えられません、、。ジャンプの高さの変え方を教えてください。
ぽんかんに質問したところ、アニメーションをいじるのは難しそうだと言われました。解決方法はありますか？

**Comment by Ayarin226** [comment]
アニメーションでジャンプしてるのと同時に不自然にならないくらいにy座標を高くする、くらいしか思いつかないですね……
ジャンプが高いアニメーションを探すのも良いと思いますー

**Comment by moooe** [comment]
わかりました！ありがとうございます！試してみます！

**Comment by moooe** [comment]
スクリプトを書いて試みたのですが、再生してもらうとわかると思うのですが、ジャンプすると地面ごと揺れてしまいます。値を変えて調節しても揺れるのは変えられません。解決方法はあるでしょうか。

**Comment by TomTomTommy** [comment]
ジャンプをするごとに地面が揺れるっていうのは、画面がなんとなくカクカク動いていることを指しているのかな？？　だとしたら、それはコルーチンを使っているせいだと思うから、コルーチン使わずにジャンプしているように見せるやり方が良いかもです><

**Comment by moooe** [comment]
はい！そうです！画面ごと動いてしまいます。
確かにコルーチン使ってます。このコード、他の人に教えてもらったのですが、コルーチンを使わないやり方のコードを教えてもらえますか？
今コルーチンのことを調べたのですが自分で修復できそうにありません、、

**Comment by Ayarin226** [comment]
かくかくするのはコルーチンを使っているから、というよりかは
コルーチン内での計算方法の問題かな？

例えばこんな感じに、座標を徐々に上にあげて行く感じにしてあげればカクカクはしなくなると思うよ。
この方法だと、落ちるときに重力を使っているので着地のときにブレてしまうから、RigidbodyからRotationとかを固定しないといけないけど！

```
        if (Input.GetKeyDown(KeyCode.UpArrow) && !animator.GetBool("JUMP"))
        {
            animator.SetBool("JUMP", true);
            Invoke("JumpToRun", .7f);
            rb.AddForce(0, jumpForce, 0);
            jumpFlag = true;
        }

        if (jumpFlag)
        {
            Debug.Log("jump");
            jumpTime += Time.deltaTime;
            if (jumpTime < 1)
            {
                Debug.Log("up");
                transform.position += Vector3.up * Time.deltaTime * 3;
            }
            else
            {
                jumpFlag = false;
                jumpTime = 0;
            }
        }
```

**Comment by moooe** [comment]
無事、実装できました。Rigidbody外したら解決しました！！！
丁寧に提案していただいてありがとうございました！
