### ISSUE TITLE
ステージ生成の終わり方について

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#3]
今、ステージを自動生成してそこを走らせているのですが、時間制限をつけて制限時間になったらゲームが終了するようにしようとしています。そこで、制限時間になったときとゴールに来た時にステージの生成が終わるようにしたいのですがどのように実装したらいいか教えていただきたいです。
また、ループ生成するようにしているのでどのようにゴールを作ったらいいか思いつかないので教えて頂きたいです。

**Comment by Ayarin226** [comment]
ゴールだけループさせないですでに先の方に置いておけば良いんじゃないかな？

**Comment by moooe** [comment]
あ、なるほど！それでやってみます！

**Comment by Ayarin226** [comment]
それかゴールの座標にある程度近づいたら生成するか、どっちかかな？
できなかったらまた言ってね〜

**Comment by moooe** [comment]
わかりました！ありがとうございます！

**Comment by moooe** [comment]
ゴールは実装できたのですが、ゴールを置く位置の調節などが必要です！あと、n回生成したら生成をストップするってやり方もアリかなって思いました。またこれから調整していきます。
