### ISSUE TITLE
ボタンを押したらゲームをスタートさせたい！

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#4]
夜分遅くにすみません。

今、最初の画面でGOというボタンをおすと、ゲーム画面に移動するようにしています。そこから、Startのボタンを押したら実際にゲームが始まるようにしたいです。

現状は、新しくスクリプトを用意し、スタートボタンを押すと消えるようにするところまでは出来ています。

ボタンを押したら、PlayerScriptを呼び出すようにしたらいいのかなと思い調べたのですが、調べ方が悪いのかもしれませんがわかりませんでした。どうしたらよいでしょうか？

**Comment by Ayarin226** [comment]
PlayerScriptを呼び出すとはどういう意味だろう？
ボタンを押したら、Prefabとして持っているPlayerをInstantiateすれば良いのかなって気もします！

**Comment by moooe** [comment]
他のスクリプトから、”もしボタンを押したらこのスクリプトを実行する”とかいうのが出来るのかな～と勝手に思っただけです！調べて出てこなかったからできないんですね、、

すみません、どういうことですか？泣

**Comment by Ayarin226** [comment]
スクリプトを実行する、というのはどういう意味をさしているんだろう？
シーン上にスクリプトがついているオブジェクトが表示された瞬間にそのスクリプトのStart()やUpdate()は実行されるよ。
関数を呼び出すという意味かな？

**Comment by moooe** [comment]
ああ、なるほど！！スクリプトがついてるオブジェクトのことを考えないとだめってことですね！
んん、そういうことになると思います、、

**Comment by Ayarin226** [comment]
えっと、スタートボタンを押す前にPlayerが動いちゃうのがいやで、
スタートボタンを押したらPlayerが動くようにしたいっていう解釈であってる？

**Comment by moooe** [comment]
はい！そうです！
イメージとしては、ピタゴラゲームの拡張課題みたいにボタンを押すと始まるようにしたいです！

**Comment by Ayarin226** [comment]
なるほど、一番手っ取り早いのは
Inspector上から `PlayerScript` の横のチェックを外して非表示にしておいて、
ボタンが押されたら `PlayerScript.enabled = true;` として
別のスクリプトからInspector上の `PlayerScript` の横にチェックを入れてあげる命令をするのが良いかも！

**Comment by moooe** [comment]
なるほど！！やってみました！

`PlayerScript.enabled = true;`と書いたら赤い波線でエラーになったのですが、上のほうに何か書かないといけないんですかね？

**Comment by Ayarin226** [comment]
PlayerScriptとスクリプト中に記載してもどのPlayerScriptなのかがわからないため、エラーに。
（PlayerScriptがついたゲームオブジェクトが複数存在することもあるし、存在しないこともあるため）

なので、enabledをtrueにしたいPlayerScriptがどれなのかを明示的に教えてあげる必要がありますね。

解決方法としては

1. `public PlayerScript playerScript;`と変数宣言をしておき、インスペクター上でアタッチを行なっておき、`playerScript.enabled = true;`とする
1. `GetComponent`を使用する

どちらかを行うことで、PlayerScriptを外部から操作することが可能になりますよ！

**Comment by moooe** [comment]
ありがとうございます！理解出来ました！
１番をやってみたのですが、インスペクター上でPlayerScriptのアタッチができません、、。
以下、自分が書いたコードです。原因を教えてください。
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartClickScript : MonoBehaviour {
	public GameObject button;
	public GameObject text;
	public PlayerScript PlayerScript;

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		if (Input.GetMouseButtonDown(0)){
			Destroy (button);
			Destroy (text);
			PlayerScript.enabled = true;
			
		}
		
	}
}
`

**Comment by moooe** [comment]
ちなみに、再生するとこのようなエラーがでます、、

NullReferenceException: Object reference not set to an instance of an object
StartClickScript.Update () (at Assets/Scripts/StartClickScript.cs:20)

**Comment by Ayarin226** [comment]
変数名が型名と同じなのはよくないかな！

**Comment by moooe** [comment]
あ、ほんとですね！ありがとうございます！
でもまだアタッチが出来ないのとエラーがなおりません、、

**Comment by Ayarin226** [comment]
```
void Update () {
	if (Input.GetMouseButtonDown(0)){
		Destroy (button);
		Destroy (text);
		PlayerScript.enabled = true;
		
	}
	
}
```
のPlayerScriptも変更した変数名に直したかな？

**Comment by moooe** [comment]
はい、今この状態です！

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartClickScript : MonoBehaviour {
	public GameObject button;
	public GameObject text;
	public PlayerScript playerScript;

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		if (Input.GetMouseButtonDown(0)){
			Destroy (button);
			Destroy (text);
			playerScript.enabled = true;
			
		}
		
	}
}
`

**Comment by Ayarin226** [comment]
インスペクターに `playerScript` って表示されないかな？

**Comment by moooe** [comment]
表示はされます。
<img width="960" alt="2018-05-15" src="https://user-images.githubusercontent.com/37929999/40052196-43414c1a-5878-11e8-8a75-f70a1b455d1c.png">

**Comment by moooe** [comment]
でもドロップ＆ドラッグができません。涙

**Comment by Ayarin226** [comment]
何をアタッチしようとしている？
`PlayerScript` がついているオブジェクト（今回は女の子）をアタッチするのが正解だよー？

**Comment by moooe** [comment]
あ！そういうことですか！PlayerScript自体をアタッチしようとしていました、、、
すみません。解決しました。

このままだと、タイマーなどはスタートボタンを押さなくても進んでしまうので、同じようにしたらできるでしょうか？

**Comment by Ayarin226** [comment]
できたのならばよかったー！
プロジェクトビューにあるスクリプトは、シーン上に置いてあるものにくっついているスクリプトとは個体としては別物なので、気をつけよう！
同じようにしてみましょうー！

**Comment by moooe** [comment]
わかりました！一つ知識が増えました！！
同じようにしたら出来ました！ありがとうございます！
