### ISSUE TITLE
アニメーションについて！

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#5]
さっき、ボタンを押したらゲームがスタートするようには出来たのですが、今のままだと、ボタンを押さなくても走っているアニメーションになっているので、ボタンを押す前は他の立っているアニメーションにして、ボタンを押すと走り出すようにしたいです。

今、Animatorにその立っているアニメーション（Idle）を追加し、スクリプトも自分なりに書いてみたのですが、再生するとIdleのアニメーションは上手くいったのですが、ボタンを押しても走っているアニメーションが実行されず、ジャンプを何回かすれば走っているアニメーションになります。どうしたらよいでしょうか？

以下、追加したコードとAnimatorのスクショです。
` if (Input.GetMouseButtonDown(0)){
            animator.SetBool("RUN",true);
        }`
<img width="960" alt="2018-05-15 1" src="https://user-images.githubusercontent.com/37929999/40053993-3c0fed42-587e-11e8-974d-b45b577fc057.png">

**Comment by Ayarin226** [comment]
マウスのボタンを押したらアニメーションが変わるようになっているけどそれはあってる？

**Comment by moooe** [comment]
スタートボタンのスクリプトを書いたときに同じようにかいたので、そう書けば”スタートボタンをクリックしたときに、、”という条件になるかなとおもって書きました

**Comment by Ayarin226** [comment]
スタートボタンのスクリプトってどう書いたのだろう？

**Comment by Ayarin226** [comment]
`playerScript.enable = true` にした時と同じようにかけば良いよ！

**Comment by moooe** [comment]
スタートボタンにつけているスクリプトの全文です。

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class StartClickScript : MonoBehaviour {
	public GameObject button;
	public GameObject text;
	public PlayerScript playerScript;
	public TimeScript timeScript;
	public CreateScript createScript;
	public Text goalText;


	// Use this for initialization
	void Start () {
		goalText.enabled = false; // テキストを非表示にしておく
		
	}
	
	// Update is called once per frame
	void Update () {
		if (Input.GetMouseButtonDown(0)){
			Destroy (button);
			Destroy (text);
			playerScript.enabled = true;
			timeScript.enabled = true;
			createScript.enabled = true;
			
		}
		
	}
}
`

**Comment by moooe** [comment]
同じようにするとはどういうことでしょうか？
いじるのはアニメーションのことを書いている、PlayerScriptですか？

**Comment by Ayarin226** [comment]
そもそもスタートボタンにつけているスクリプトが間違っているかな。
それだとボタン関係なくどこでもマウス押されたら反応してしまうよ。
あと、
`if (Input.GetMouseButtonDown(0)){ animator.SetBool("RUN",true); }`
って `PlayerScript` に書いてないかな？
`PlayerScript` が非表示な状態だから `if (Input.GetMouseButtonDown(0)){ animator.SetBool("RUN",true); }` がきちんと動作しないんだと思うよ

**Comment by Ayarin226** [comment]
ボタンを押したら〜っていうのはStopGameの教科書を見直してみよう！

**Comment by moooe** [comment]
ボタンをおしたら～というのは教科書をみなおしてみます。

あと、ボタンを押したら～という風にしたいのなら、最初はPlayerScriptのチェックを外して非表示にしておく必要があるんですよね？そうなると、`if (Input.GetMouseButtonDown(0)){ animator.SetBool("RUN",true); }`を動作させるのは不可能ということですか？

**Comment by Ayarin226** [comment]
今のうちにスクリプトのひとつひとつがどのタイミングで実行されるのか、というのを確認し直した方が良いかもしれないですね。

ボタンが押されたら走っているアニメーションにしたいのならば
`PlayerScript` の `Start()` のなかに `animator.SetBool("RUN",true);` と書けば良いかと。
`Start()` というのはスクリプトが有効になった瞬間に呼ばれるものなので、
`playerScript.enable = true;` にした瞬間に呼ばれることになります。

**Comment by moooe** [comment]
Updateのなかでなく、Startの中に書き直したらできました！解決です。ありがとうございまいした。
