### ISSUE TITLE
Retryボタンを作りたい！

### ISSUE THREAD

**Issue by moooe** [moooe/HajimetenoOtukai#6]
質問だらけですみません、、、。

ゴールした時やゲームオーバーになったときに、Retryボタンを出現させて押したらスタート画面に戻るようにしたいです。

UnityRunを参考にしようと思い、スクリプトをみたところ、LoadScene？でやっていたのですが、UnityRunではどういう考え方でRetryボタンを出しているのでしょうか。

**Comment by Ayarin226** [comment]
環境を活用していてすごく良いと思うのでどんどん質問してね！
GameOverと同時にCanavasを表示（ `SetActive(true)` ）していたと思います！

**Comment by moooe** [comment]
よかったです！活用します！

なるほど！やってみたのですがわかりません、、。
再生したときにRetryボタンを非表示にしたい（おそらくそれができれば、ゲームオーバーになったときにRetryボタンが出てくるという実装は出来ていると思います。）というのと、Retryを押したらゲームのスタート画面に戻りたいです。教えて下さい。

**Comment by Ayarin226** [comment]
新しくCanvasを作って、
常に非表示（インスペクターから一番左上の、名前の横にあるチェックを外しておく）にして置いて、
ゲームオーバーしたらCanvasを表示（ `SetActive(true)` ）してあげれば良いと思います。
Retryの実装は、UnityRunのボタンにどんな関数が紐づけられているか確認すればわかると思います。
ボタンを押した時に、今のシーンを読み込み直せば良いです。（ `SceneMangaer` ）

**Comment by moooe** [comment]
ありがとうございます！

今やってみているのですが、SetActiveがエラーで赤線を引かれているのですがどうしてでしょうか。

**Comment by Ayarin226** [comment]
エラー文とコード見せて貰えないとなんともいえません……

**Comment by moooe** [comment]
`using System.Collections;
using UnityEngine.UI;
using UnityEngine;

public class TimeScript : MonoBehaviour {
	private float time = 50;
    public PlayerScript playerScript;
	
	public GameObject gameOverText; 
	RetryScript retryscript;
	public Canvas canvas2;

	bool flag=true;
	

	// Use this for initialization
	void Start () {
		gameOverText.SetActive(false);
		canvas2.SetActive(false);
		GetComponent<Text>().text = "TIME : " + ((int)time).ToString();
	}
	
	// Update is called once per frame
	void Update () {
		
        if (playerScript.isGoal) // もしPlayerScriptのisGoalがTrueだったら
        {
			flag=false;
        }
        
		if(flag){
		time -= Time.deltaTime;
		}
		if (time < 0) {
			GameOver();
			retryscript.Retry();
		}
		if (time < 0) time = 0;
		GetComponent<Text>().text = "TIME : " + ((int)time).ToString ();
	}
	void GameOver () {
		canvas2.SetActive(true);
		gameOverText.SetActive(true);
		playerScript.Stop2();
	}
}
`
{
	"resource": "/c:/Users/m_exp/Desktop/HajimetenoOtukai/Assets/Scripts/TimeScript.cs",
	"owner": "csharp",
	"code": "undefined",
	"severity": 8,
	"message": "'Canvas' does not contain a definition for 'SetActive' and no extension method 'SetActive' accepting a first argument of type 'Canvas' could be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp]",
	"startLineNumber": 19,
	"startColumn": 11,
	"endLineNumber": 19,
	"endColumn": 20
}

**Comment by moooe** [comment]
すみません！これです！！

**Comment by Ayarin226** [comment]
エラー文はどんな感じ？
Null Reference かな？何行目で出てるのかも教えて欲しい！

**Comment by moooe** [comment]
こんな感じです！
19行目と42行目です。

<img width="960" alt="2018-05-16" src="https://user-images.githubusercontent.com/37929999/40067911-48b7611e-58a2-11e8-9964-d279dad6e19c.png">

**Comment by Ayarin226** [comment]
canvas2はCavas型ではなくて、GameObject型で大丈夫です！
表示非表示を変更したいだけなので。

**Comment by moooe** [comment]
なるほど！ゲームオーバーになったらRetryボタン表示されるようになりました！

**Comment by moooe** [comment]
ゲーム画面に戻るのも出来ました！

やっとUnityの仕組みもC#言語もわかってきました！頑張ります！！

**Comment by Ayarin226** [comment]
良かったー！
何か気になることでも気軽に聞いて！
今のうちにどんどん覚えていこう！

**Comment by moooe** [comment]
ほんとにありがとうございます！！
どしどし聞いちゃいます！
